### ISSUE TITLE
Redirect Problem

### ISSUE THREAD

**Issue by superuser123** [habibialkaff/Copy-.Net-SDK#1]
Hi, I'm developing an app on the copy cloud.
But there is a problem.
While authentication, it gets request token without a problem, but it redirects to wrong 
redirects to wrong url(www.copy.com).
I set the callback url to a www.google.com(for test), but it redirects to www.copy.com.
Please help me.

**Comment by habibialkaff** [comment]
Sorry I haven't worked on this repo for quite a while. And since Copy is closing down, I don't think working on it will give any benefit

https://techlib.barracuda.com/Copy/EndOfLife
